dist: trusty
sudo: required

language: cpp
compiler:
  - gcc
  - clang
cache: apt

git:
  submodules: false

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cppcheck freeglut3-dev
  - sudo apt-get install -qq libopenal-dev libalut-dev libvorbis-dev libogg-dev
  - sudo apt-get install -qq liblua5.1-0-dev libgettextpo-dev libboost-all-dev
  - sudo apt-get install -qq libqt4-opengl-dev
  - sudo apt-get install -qq libglew-dev
  - sudo apt-get install -qq libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev

install:
  # Clang is not system wide. This is a workaround.
  - $CC --version
  - which $CC
  - export CC=`which $CC`

  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq "g++-${GCC_VERSION}"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi

  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq "libstdc++-${GCC_VERSION}-dev"; fi

script:
  # Force the update of the submodule manually
  - git submodule update --init --recursive --force --remote

  - cmake -DCMAKE_CXX_COMPILER=$(which $CXX) -DDEBUG_FEATURES=ON .
  - make translations
  - make -j2 valyriatear

after_script:
  - cppcheck --verbose --enable=all --quiet `git ls-files src/\*.h src/\*.cpp`
  - tools/encoding-tests.sh src/*

notifications:
  email:
    recipients:
      - yohann.ferreira@orange.fr
    on_success: change
    on_failure: always
