language: cpp
compiler:
  - gcc
  - clang
git:
  submodules: false
cache: apt
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cppcheck freeglut3-dev
  - sudo apt-get install -qq libopenal-dev libalut-dev libvorbis-dev libogg-dev
  - sudo apt-get install -qq liblua5.1-0-dev libgettextpo-dev libboost-all-dev
  - sudo apt-get install -qq libqt4-opengl-dev
  - sudo apt-get install -qq libglew-dev
  
  - wget http://www.libsdl.org/release/SDL2-2.0.3.tar.gz -O - | tar xz
  - (cd SDL2-2.0.3 && ./configure --prefix=/usr && sudo -i make -j5 && sudo -i make install)
  - wget http://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.0.tar.gz -O - | tar xz
  - (cd SDL2_image-2.0.0 && ./configure --prefix=/usr && sudo -i make -j5 && sudo -i make install)
  - wget http://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.12.tar.gz -O - | tar xz
  - (cd SDL2_ttf-2.0.12 && ./configure --prefix=/usr && sudo -i make -j5 && sudo -i make install)
  
script:
  # Clang is not system wide.  This is a work around.
  - $CC --version
  - which $CC
  - export CC=`which $CC`
  
  - cmake -DDEBUG_FEATURES=ON -DEDITOR_SUPPORT=ON .
  - make -j2 vt-editor
  - make translations
  - make -j2 valyriatear
branches:
  only:
    - master
after_script: cppcheck --verbose --enable=all --quiet `git ls-files src/\*.cpp`
notifications:
  email:
    recipients:
      - yohann.ferreira@orange.fr
    on_success: change
    on_failure: always
